### PR TITLE
[WIP] lxqt-sudo: new GUI frontend for sudo

### PR DESCRIPTION
**Pull request by palinek**
closes lxde/lxqt#537

Issues:
- no icon support yet
- no information about number of attempts, etc.

### CODE REVIEW

**Comment by palinek** [comment]
Should we put `lxqt-sudo` into `lxqt-admin` or should it be a standalone component?

**Comment by palinek** [comment]
> It didn't work for me when I tried lxqt-sudo pacman -Syu

Is only `pacman` problematic? Or it doesn't work completely for you?

**Comment by paulolieuthier** [comment]
> Should we put lxqt-sudo into lxqt-admin or should it be a standalone component?

Well, ideally, IMO, it should be totally independent of LXQt. Like Screengrab is.

> > It didn't work for me when I tried lxqt-sudo pacman -Syu

> Is only pacman problematic? Or it doesn't work completely for you?

It worked for simple things. Let me update and test it further.

**Comment by palinek** [comment]
> > Should we put lxqt-sudo into lxqt-admin or should it be a standalone component?

> Well, ideally, IMO, it should be totally independent of LXQt. Like Screengrab is.

Hm... but then we loose the already implemented mechanizm for styling, translation etc..

**Comment by luis-pereira** [comment]
@palinek @paulolieuthier I can implement the translations stuff  really quickly. I have the time now.

**Comment by alfredobonino** [comment]
on cmake 3.0.2 not compile.... and there aren't a cmake minimum version...the code is good...

**Comment by alfredobonino** [comment]
i can make the translations for italian...

**Comment by palinek** [comment]
> on cmake 3.0.2 not compile.... and there aren't a cmake minimum version.

@alfredobonino can you, please, provide the error output? (I wasn't aware I was using some "fresh" features)

**Comment by alfredobonino** [comment]
The problem is : not find qt5_wrap_ui and qt5_wrap_cpp....

**Comment by luis-pereira** [comment]
@palinek @alfredobonino just compiled it without any problem.

**Comment by alfredobonino** [comment]
In ubuntu 15.04 With cmake 3.0.2 not compile.
Please,@palinek insert cmake_minimum_version() in cmakelists...

**Comment by luis-pereira** [comment]
@alfredobonino Does cmake configure lxqt-admin-time for you ? It also doesn't have an cmake_minimum_version().... and it's not necessary the top CMakeLists.txt contains ```cmake_minimum_required(VERSION 2.8.11)```

**Comment by jleclanche** [comment]
It's fine to release it with a liblxqt dependency, at least for now. We'll see where it goes afterwards and whether anyone without lxqt wants it.

But it shouldn't be in lxqt-admin, no. It's fine as a component.

**Comment by alfredobonino** [comment]
The problem is in qt5_wrap!!!!

**Comment by pmattern** [comment]
After compiling flawlessly I couldn't get lxqt-sudo to launch a GUI application (which is the only reasonable thing to do with tools like this, imho).
Using JuffEd as dummy which was working pretty well invoked as `DISPLAY=:0 sudo juffed` sometimes just a dialog window came up for milliseconds, no chance to read anything, and sometimes the regular GUI to fill in the password. Either way nothing else happened in addition.

The desktop entry file is incomplete right now as line Categories lacks a value. Not sure whether this file makes any sense at all given that lxqt-sudo is invoked with arguments varying strongly.

Arch Linux i686 or x86_64 in KVM/QEMU VMs, latest Git checkouts of all LXQt components.

**Comment by luis-pereira** [comment]
@pmattern ```lxqt-sudo gparted``` worked fine here.
@alfredobonino To get help you need to post your commands and the output.

**Comment by palinek** [comment]
Currenly I'm not 100% sure... but it seems that some programs/applications have problems when they are run by sudo as a background processes (the sudo's `-b` switch). So after they are launched, their stdin is closed (because sudo parent ended...).
It may be we need the same approach as `kdesudo` and don't use `-b` switch... instead keep our process running (and replicating stderr/stdout..) until the (privileged) child ends => our error handling needs to be changed.

**Comment by palinek** [comment]
...continueing in lxde/lxqt-sudo#1

**Pull request closed without merging**
