### PR TITLE
Use better names for dialog titles, added german translation.

### PR DESCRIPTION
**Pull request by ThomasVie**

### CODE REVIEW

**Comment by pmattern** [comment]
Not sure whether I got this right. But if you're referring to that additional string "Time and date setup" in the actual window as seen here
lxqt_lxqt-config-time_text-strings
I'd definitely prefer the screenshot posted by ThomasVie above: having a telling window title is always helpful, IMO, but sort of repeating "Time and date setup" in the window itself doesn't make sense, in particular considering that basically the same is stated in the left pane, too.
Screenshot by ThomasVie does *not* correspond to the latest changes in this PR, does it (e. g. "Time and date setup" still present in datetime.ui)?

German translation gtm, btw.

**Comment by palinek** [comment]
> But sort of repeating "Time and date setup" in the window itself doesn't make sense, in particular considering that basically the same is stated in the left pane, too.

well, then @ThomasVie, please, remove the window titles from \*.ui files

**Comment by ThomasVie** [comment]
Updated pull request.

**Comment by pmattern** [comment]
Landed in ae9468c.

Thanks a lot.

**Pull request closed without merging**
