### PR TITLE
lxqt-admin-user: set minimum default GID value for new group to 1000

### PR DESCRIPTION
**Pull request by palinek**
fix for lxde/lxqt#510

### CODE REVIEW

**Comment by jleclanche** [comment]
Can you take the occasion to put the min and max ids in a #define please

**Comment by palinek** [comment]
@jleclanche should the define be common for both user/group? Or should I put defines into userdialog.cpp & groupdialog.cpp ?

**Comment by jleclanche** [comment]
Have them separate.

**Comment by palinek** [comment]
@jleclanche moved to define. Btw, why are you prefering define over static const or enum?

**Comment by jleclanche** [comment]
I can see a world in which a distro has to redefine those at build time.

**Comment by palinek** [comment]
Wise... in that case I probably should put that in following way
```c++
#if !defined(DEFAULT_GID_MIN)
#    define DEFAULT_GID_MIN 0
#endif
```

Right?

**Comment by jleclanche** [comment]
Don't bother until we actually get a request for it.

**Pull request merged**
