### PR TITLE
Patch 5

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Comment by palinek** [comment]
I can't see any \[it\] translation in lxqt-admin-time/lxqt-admin-time.desktop after build...am I missing somthing?

**Comment by luis-pereira** [comment]
@palinek Remove the generated .desktop file and rebuild

**Comment by palinek** [comment]
@luis-pereira sure :) made that multiple times... is it building correctly for you?

**Comment by luis-pereira** [comment]
@palinek Yes It is. What I don't understand is this commit message: https://github.com/stefonarch/lxqt-admin/commit/06146442ba8556ad025177f2dd0ce2f91da91401

**Comment by palinek** [comment]
finaly got it working...
landed in 04b5874
@stefonarch thank you... and please, squash your commits in your next PRs

**Comment by stefonarch** [comment]
Sorry for the tipos... I'm not very expert in using git as you can  see.
Can you explain for dummies how to  "squash my commits in my next PRs"?
Thanks.

Il 29/03/2015 01:43, palinek ha scritto:
> finaly got it working...
> landed in 04b5874
> <https://github.com/lxde/lxqt-admin/commit/04b58742df2c879110f564bb1a7fab70c842ed65>
> @stefonarch <https://github.com/stefonarch> thank you... and please,
> squash your commits in your next PRs
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lxde/lxqt-admin/pull/20#issuecomment-87335338>.
> 

--

**Comment by palinek** [comment]
You can have a look here https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase-i for example

**Pull request closed without merging**
